version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - 3000
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: trackerdb
    ports:
      - 8080
    depends_on:
      - flyway

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/trackerdb -user=postgres -password=admin -connectRetries=60 migrate
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - db

  db:
    image: postgres:12.2
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: trackerdb
    ports:
      - 5432
